framework:
  rate_limiter:
    login_username:
      policy: 'sliding_window'
      limit: 5000
      interval: '15 minutes'
    login_ip:
      policy: 'sliding_window'
      limit: 5000
      interval: '15 minutes'
    forgot_password_ip:
      policy: 'sliding_window'
      limit: 1000     # max 10 requests
      interval: '1 hour'
      # Key will be client IP
    forgot_password_account:
      policy: 'sliding_window'
      limit: 3000       # max 3 requests
      interval: '1 hour'
      # Key will be user email (or hashed user id)
