parameters:
    .container.dumper.inline_factories: true

    app.config.title: 'Wandering the World'
    app.config.locale: 'en'

    password_reset.ttl: '%env(PASSWORD_RESET_TTL)%'
    app.public_img_path: '%env(APP_PUBLIC_IMG_PATH)%'

    app.config.twitter: 'jedi58'

    csp: ''

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    Inachis\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Migrations/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Inachis\Diagnostics\Check\:
        resource: '../src/Diagnostics/Check/*/*'
        tags: ['app.diagnostic_check']

    Inachis\Diagnostics\DiagnosticsCollector:
        arguments:
            $checks: !tagged_iterator app.diagnostic_check

    Inachis\EventListener\AdminResponseEvent:
        arguments:
            $csp: '%csp%'

    Inachis\EventListener\LoginSuccessListener:
        tags:
            - { name: 'kernel.event_listener', event: Symfony\Component\Security\Http\Event\LoginSuccessEvent }

    Inachis\EventListener\LoginFailureListener:
        tags:
            - { name: 'kernel.event_listener', event: Symfony\Component\Security\Http\Event\LoginFailureEvent }

    Inachis\Service\Image\ImageLocaliser:
        arguments:
            $publicImgPath: '%app.public_img_path%'

    Inachis\Service\Export\Page\PageExportService:
        arguments:
            $writers: !tagged_iterator inachis.export_writer

    Inachis\Service\Export\Page\PageJsonWriter:
        tags:
            - { name: 'inachis.export_writer', priority: 0 }

    Inachis\Service\Export\Page\PageMdWriter:
        tags:
            - { name: 'inachis.export_writer', priority: 0 }

    Inachis\Service\Export\Page\PageXmlWriter:
        tags:
            - { name: 'inachis.export_writer', priority: 0 }

    Inachis\Service\Export\Series\SeriesExportService:
        arguments:
            $writers: !tagged_iterator inachis.export_writer

    Inachis\Service\Export\Series\SeriesMdWriter:
        tags:
            - { name: 'inachis.export_writer', priority: 10 }

    Inachis\Service\Export\Series\SeriesXmlWriter:
        tags:
            - { name: 'inachis.export_writer', priority: 10 }

    Inachis\Service\Export\Category\CategoryExportService:
        arguments:
            $writers: !tagged_iterator inachis.export_writer

    Inachis\Service\Export\Category\CategoryXmlWriter:
        tags:
            - { name: 'inachis.export_writer', priority: 10 }

    Inachis\Service\User\PasswordResetTokenService:
        arguments:
            $appSecret: '%env(APP_SECRET)%'
            $ttlSeconds: '%password_reset.ttl%'

    Inachis\Service\VersionService:
        arguments:
            $versionFile: '%kernel.project_dir%/config/version.php'

    Inachis\Twig\:
        resource: '../src/Twig'
        tags: [ 'twig.extension' ]
        autoconfigure: true


#    Inachis\Service\CryptoService:
#        arguments:
#            $masterKey: '%env(APP_ENCRYPTION_KEY)%'

#    Inachis\EntityListener\SettingListener:
#        tags:
#            - { name: doctrine.orm.entity_listener }

#    Inachis\Service\ImageResizer\GdImageResizer: ~
#    Inachis\Service\ImageResizer\ImagickResizer: ~
    # Inachis\Service\ImageResizer\ImageResizerInterface:
    #     factory: ['Inachis\Service\ImageResizer\ImageResizerFactory', 'create']
    #     public: true
